<?php

declare(strict_types=1);

namespace RemcoSmitsDev\BuildableSerializerBundle\Normalizer;

/**
 * Marker interface for all normalizer classes generated by the Buildable Serializer Bundle.
 *
 * Every PHP normalizer emitted by {@see \RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator}
 * must implement this interface. The presence of this interface is the sole criterion used by
 * {@see \RemcoSmitsDev\BuildableSerializerBundle\DependencyInjection\Compiler\RegisterGeneratedNormalizersPass}
 * to identify which classes in the generated classmap should be registered as Symfony Serializer
 * normalizer services.
 *
 * Implementing classes are automatically tagged with `serializer.normalizer` at a high priority
 * so they take precedence over Symfony's built-in reflection-based normalizers for the domain
 * models they handle.
 *
 * Example generated normalizer skeleton:
 *
 * ```php
 * final class UserNormalizer implements GeneratedNormalizerInterface, NormalizerInterface
 * {
 *     public function normalize(mixed $object, ?string $format = null, array $context = []): array { ... }
 *     public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool { ... }
 * }
 * ```
 *
 * @see \RemcoSmitsDev\BuildableSerializerBundle\DependencyInjection\Compiler\RegisterGeneratedNormalizersPass
 * @see \RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator
 * @see \RemcoSmitsDev\BuildableSerializerBundle\CacheWarmer\NormalizerCacheWarmer
 */
interface GeneratedNormalizerInterface {}
