<?php

declare(strict_types=1);

namespace RemcoSmitsDev\BuildableSerializerBundle\Tests\Unit\Generator;

use RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerGenerator;
use RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerPathResolver;
use RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerWriter;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\AbstractTestCase;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\AddressFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\NamespaceA\User as UserA;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\NamespaceB\User as UserB;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\PersonFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\SerializedNameFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\SetterFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\SimpleBlog;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\StatusFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\TagFixture;
use RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\WitherFixture;

/**
 * @covers \RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerGenerator
 * @covers \RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerPathResolver
 * @covers \RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerWriter
 */
final class DenormalizerGeneratorTest extends AbstractTestCase
{
    private string $tempDir;
    private DenormalizerGenerator $generator;
    private DenormalizerWriter $writer;
    private DenormalizerPathResolver $pathResolver;

    protected function setUp(): void
    {
        $this->tempDir = $this->createTempDir();
        $this->generator = $this->makeDenormalizerGenerator();
        $this->writer = $this->makeDenormalizerWriter($this->tempDir);
        $this->pathResolver = $this->makeDenormalizerPathResolver($this->tempDir);
    }

    protected function tearDown(): void
    {
        $this->removeTempDir($this->tempDir);
    }

    public function testGenerateReturnsValidPhpCode(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringStartsWith('<?php', $code);
    }

    public function testGeneratedCodeHasStrictTypesByDefault(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('declare(strict_types=1)', $code);
    }

    public function testGeneratedCodeOmitsStrictTypesWhenFeatureDisabled(): void
    {
        $generator = new DenormalizerGenerator(
            metadataFactory: $this->makeMetadataFactory(),
            generatedNamespace: self::GENERATED_NAMESPACE,
            features: [
                'groups' => true,
                'attributes' => true,
                'strict_types' => false,
            ],
        );

        $metadata = $generator->getMetadataFactory()->getMetadataFor(SimpleBlog::class);
        $code = $generator->generate($metadata);

        $this->assertStringNotContainsString('declare(strict_types=1)', $code);
    }

    public function testGeneratedCodeHasCorrectNamespace(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('namespace BuildableTest\\Generated', $code);
    }

    public function testGeneratedCodeHasDenormalizerClassWithHashedShortName(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertMatchesRegularExpression('/class N[a-f0-9]{8}_SimpleBlogDenormalizer/', $code);
    }

    public function testGeneratedClassIsFinal(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertMatchesRegularExpression('/final class N[a-f0-9]{8}_SimpleBlogDenormalizer/', $code);
    }

    public function testGeneratedCodeHasGeneratedTag(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('@generated', $code);
    }

    public function testGeneratedCodeIncludesAutoGeneratedWarning(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('AUTO-GENERATED', $code);
    }

    public function testGeneratedCodeImplementsDenormalizerInterface(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('DenormalizerInterface', $code);
    }

    public function testGeneratedCodeImplementsDenormalizerAwareInterface(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('DenormalizerAwareInterface', $code);
    }

    public function testGeneratedCodeImplementsGeneratedDenormalizerInterface(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('GeneratedDenormalizerInterface', $code);
    }

    public function testGeneratedCodeUsesGeneratedDenormalizerTrait(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('use GeneratedDenormalizerTrait', $code);
    }

    public function testGeneratedCodeUsesDenormalizerAwareTrait(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('use DenormalizerAwareTrait', $code);
    }

    public function testGeneratedCodeHasDenormalizeMethod(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('public function denormalize(', $code);
    }

    public function testGeneratedCodeHasConstructMethod(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('private function construct(', $code);
    }

    public function testGeneratedCodeHasPopulateMethod(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('private function populate(', $code);
    }

    public function testGeneratedCodeHasSupportsDenormalizationMethod(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('public function supportsDenormalization(', $code);
    }

    public function testGeneratedCodeHasGetSupportedTypesMethod(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('public function getSupportedTypes(', $code);
    }

    public function testDenormalizeMethodHonoursObjectToPopulate(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('AbstractNormalizer::OBJECT_TO_POPULATE', $code);
    }

    public function testDenormalizeMethodDelegatesToConstructAndPopulate(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('$this->construct(', $code);
        $this->assertStringContainsString('$this->populate(', $code);
    }

    public function testDenormalizeMethodReturnTypeIsTargetClass(): void
    {
        $code = $this->generate(SimpleBlog::class);

        // denormalize(): SimpleBlog — the return type must match the target.
        $this->assertMatchesRegularExpression('/public function denormalize\([^)]*\): SimpleBlog\b/', $code);
    }

    public function testConstructMethodUsesNamedArguments(): void
    {
        // SimpleBlog has constructor params id/title/content/excerpt — the
        // generator must emit named arguments for every one of them so the
        // call is robust against reorderings in the domain class.
        // With the attributes feature enabled the named arg value is a ternary,
        // so we assert on the param name appearing before the extract call.
        $code = $this->generate(SimpleBlog::class);

        $this->assertMatchesRegularExpression('/\bid:\s.*\$this->extract/', $code);
        $this->assertMatchesRegularExpression('/\btitle:\s.*\$this->extract/', $code);
        $this->assertMatchesRegularExpression('/\bcontent:\s.*\$this->extract/', $code);
        $this->assertMatchesRegularExpression('/\bexcerpt:\s.*\$this->extract/', $code);
    }

    public function testConstructMethodPicksIntExtractorForIntParam(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString("\$this->extractInt(\$data, 'id'", $code);
    }

    public function testConstructMethodPicksStringExtractorForStringParam(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString("\$this->extractString(\$data, 'title'", $code);
        $this->assertStringContainsString("\$this->extractString(\$data, 'content'", $code);
    }

    public function testConstructMethodPicksNullableStringExtractorForNullableParam(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString("\$this->extractNullableString(\$data, 'excerpt'", $code);
    }

    public function testConstructMethodMarksRequiredParametersAsRequired(): void
    {
        $code = $this->generate(SimpleBlog::class);

        // id / title / content are required (no default, not nullable).
        $this->assertMatchesRegularExpression("/extractInt\\(\\\$data, 'id', required: true/", $code);
        $this->assertMatchesRegularExpression("/extractString\\(\\\$data, 'title', required: true/", $code);
        $this->assertMatchesRegularExpression("/extractString\\(\\\$data, 'content', required: true/", $code);
    }

    public function testConstructMethodMarksOptionalParametersAsNotRequired(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertMatchesRegularExpression("/extractNullableString\\(\\\$data, 'excerpt', required: false/", $code);
    }

    public function testConstructMethodEmitsIntDefault(): void
    {
        $code = $this->generate(PersonFixture::class);

        // PersonFixture::$age has default 18.
        $this->assertMatchesRegularExpression("/extractInt\\(\\\$data, 'age', required: false, default: 18/", $code);
    }

    public function testConstructMethodEmitsNullDefault(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('default: null', $code);
    }

    public function testConstructMethodEmitsEnumCaseAsFullyQualifiedConstant(): void
    {
        $code = $this->generate(PersonFixture::class);

        // PersonFixture::$status has default StatusFixture::PENDING. The
        // generated file must reference it via a fully-qualified class
        // constant so the emitted code is independent of the `use`
        // statements at the top of the file.
        $this->assertStringContainsString('default: \\' . StatusFixture::class . '::PENDING', $code);
    }

    public function testConstructMethodReturnsNewInstanceWithShortName(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('return new SimpleBlog(', $code);
    }

    public function testConstructMethodEmitsBareNewWhenNoConstructor(): void
    {
        // SetterFixture has an implicit/empty constructor.
        $code = $this->generate(SetterFixture::class);

        $this->assertMatchesRegularExpression('/return new SetterFixture\s*\(\s*\)/', $code);
    }

    public function testConstructMethodEmitsClassConstForNestedObjectParameter(): void
    {
        $code = $this->generate(PersonFixture::class);

        // PersonFixture::$address uses AddressFixture::class as the type hint.
        $this->assertStringContainsString('AddressFixture::class', $code);
    }

    public function testPopulateMethodEmitsConditionalSkipMap(): void
    {
        $code = $this->generate(SimpleBlog::class);

        // The skip map must be gated behind OBJECT_TO_POPULATE so partial
        // updates on a populate object still write every field present in
        // the input payload.
        $this->assertMatchesRegularExpression(
            '/\$skip\s*=\s*isset\(\$context\[AbstractNormalizer::OBJECT_TO_POPULATE\]\)/',
            $code,
        );
        $this->assertStringContainsString('array_fill_keys(', $code);
    }

    public function testPopulateMethodSkipMapContainsConstructorParamKeys(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString("['id', 'title', 'content', 'excerpt']", $code);
    }

    public function testPopulateMethodGuardsEachFieldWithArrayKeyExists(): void
    {
        $code = $this->generate(SetterFixture::class);

        // SetterFixture has no constructor params, so populate() handles
        // every field through setters, each of which must be gated behind
        // an array_key_exists() check.
        preg_match_all("/array_key_exists\\('(\\w+)', \\\$data\\)/", $code, $matches);

        $this->assertContains('name', $matches[1]);
        $this->assertContains('age', $matches[1]);
        $this->assertContains('email', $matches[1]);
    }

    public function testPopulateMethodEmitsSetterCallsForSetterMutators(): void
    {
        $code = $this->generate(SetterFixture::class);

        $this->assertStringContainsString('$object->setName(', $code);
        $this->assertStringContainsString('$object->setAge(', $code);
        $this->assertStringContainsString('$object->setEmail(', $code);
    }

    public function testPopulateMethodEmitsWitherReassignmentForWitherMutators(): void
    {
        $code = $this->generate(WitherFixture::class);

        // Withers must reassign $object because they produce a new instance.
        $this->assertStringContainsString('$object = $object->withTitle(', $code);
        $this->assertStringContainsString('$object = $object->withBody(', $code);
        $this->assertStringContainsString('$object = $object->withSlug(', $code);
    }

    public function testPopulateMethodEmitsPublicPropertyAssignmentForPublicProperty(): void
    {
        $code = $this->generate(PersonFixture::class);

        // PersonFixture::$nickname is a public promoted param with no setter,
        // so its mutator should be a direct property write.
        $this->assertStringContainsString('$object->nickname = ', $code);
    }

    public function testPopulateMethodReturnsObjectAtEnd(): void
    {
        $code = $this->generate(SetterFixture::class);

        $this->assertMatchesRegularExpression('/return \$object;/', $code);
    }

    public function testPopulateMethodSkipMapSurvivesIssetLookup(): void
    {
        // Use PersonFixture here because it has BOTH constructor parameters
        // (which populate the skip map) AND populate-phase fields (which
        // consult it). SetterFixture has an empty constructor, so its
        // populate() method carries no skip map at all.
        $code = $this->generate(PersonFixture::class);

        // The individual field guards must consult $skip with isset() — not
        // array_key_exists — so the optimisation runs in O(1).
        $this->assertStringContainsString("!isset(\$skip['", $code);
    }

    public function testSupportsDenormalizationReturnsTrueForExactMatch(): void
    {
        $code = $this->generate(SimpleBlog::class);

        // The check is an identical-to on the $type argument.
        $this->assertMatchesRegularExpression("/return \\\$type === '[^']*SimpleBlog';/", $code);
    }

    public function testGetSupportedTypesReturnsTargetClassMappedToTrue(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertMatchesRegularExpression("/\\['[^']*SimpleBlog' => true\\]/", $code);
    }

    public function testGeneratedCodeImportsTargetClass(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('use ' . SimpleBlog::class . ';', $code);
    }

    public function testGeneratedCodeImportsNestedClasses(): void
    {
        $code = $this->generate(PersonFixture::class);

        $this->assertStringContainsString('use ' . AddressFixture::class . ';', $code);
        $this->assertStringContainsString('use ' . StatusFixture::class . ';', $code);
    }

    public function testGeneratedCodeImportsAbstractNormalizer(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString('use Symfony\\Component\\Serializer\\Normalizer\\AbstractNormalizer;', $code);
    }

    public function testGeneratedCodeImportsDenormalizerAwareInterface(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString(
            'use Symfony\\Component\\Serializer\\Normalizer\\DenormalizerAwareInterface;',
            $code,
        );
    }

    public function testGeneratedCodeImportsDenormalizerAwareTrait(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString(
            'use Symfony\\Component\\Serializer\\Normalizer\\DenormalizerAwareTrait;',
            $code,
        );
    }

    public function testGeneratedCodeImportsDenormalizerInterface(): void
    {
        $code = $this->generate(SimpleBlog::class);

        $this->assertStringContainsString(
            'use Symfony\\Component\\Serializer\\Normalizer\\DenormalizerInterface;',
            $code,
        );
    }

    public function testUseStatementsAreSortedAlphabetically(): void
    {
        $code = $this->generate(PersonFixture::class);

        preg_match_all('/^use ([^;]+);/m', $code, $matches);

        $uses = $matches[1];
        $sorted = $uses;
        sort($sorted);

        $this->assertSame($sorted, $uses, 'Use statements should be sorted alphabetically.');
    }

    public function testGeneratedCodeUsesArrayOfObjectsExtractorForTypedCollection(): void
    {
        $code = $this->generate(\RemcoSmitsDev\BuildableSerializerBundle\Tests\Fixtures\Model\UserFixture::class);

        // UserFixture::$tags is typed as array<TagFixture>.
        $this->assertStringContainsString('$this->extractArrayOfObjects', $code);
        $this->assertStringContainsString('TagFixture::class', $code);
    }

    public function testWriterWritesFileAtResolvedPath(): void
    {
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(SimpleBlog::class);

        $path = $this->writer->write($metadata);

        $this->assertFileExists($path);
        $this->assertSame($path, $this->pathResolver->resolveFilePath($metadata));
    }

    public function testWrittenFileContainsGeneratedCode(): void
    {
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(SimpleBlog::class);
        $expected = $this->generator->generate($metadata);

        $path = $this->writer->write($metadata);
        $actual = (string) file_get_contents($path);

        $this->assertSame($expected, $actual);
    }

    public function testWriterCreatesTargetDirectoryIfMissing(): void
    {
        // Nest the cache dir one level deeper than what was pre-created in
        // setUp() so the writer is forced to mkdir it.
        $nestedDir = $this->tempDir . DIRECTORY_SEPARATOR . 'nested' . DIRECTORY_SEPARATOR . 'cache';

        $writer = $this->makeDenormalizerWriter($nestedDir);
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(SimpleBlog::class);

        $path = $writer->write($metadata);

        $this->assertFileExists($path);
        $this->assertDirectoryExists($nestedDir);
    }

    public function testWriterWriteAllReturnsEveryPath(): void
    {
        $factory = $this->generator->getMetadataFactory();

        $metadataCollection = [
            $factory->getMetadataFor(SimpleBlog::class),
            $factory->getMetadataFor(PersonFixture::class),
            $factory->getMetadataFor(TagFixture::class),
        ];

        $paths = $this->writer->writeAll($metadataCollection);

        $this->assertCount(3, $paths);
        foreach ($paths as $path) {
            $this->assertFileExists($path);
        }
    }

    public function testWriterWriteAllPreservesInputOrder(): void
    {
        $factory = $this->generator->getMetadataFactory();

        $metadataCollection = [
            $factory->getMetadataFor(TagFixture::class),
            $factory->getMetadataFor(SimpleBlog::class),
        ];

        $paths = $this->writer->writeAll($metadataCollection);

        $this->assertStringContainsString('TagFixtureDenormalizer.php', $paths[0]);
        $this->assertStringContainsString('SimpleBlogDenormalizer.php', $paths[1]);
    }

    public function testGeneratedFilesForDifferentNamespacesHaveDifferentClassNames(): void
    {
        $factory = $this->generator->getMetadataFactory();

        $metadataA = $factory->getMetadataFor(UserA::class);
        $metadataB = $factory->getMetadataFor(UserB::class);

        $codeA = $this->generator->generate($metadataA);
        $codeB = $this->generator->generate($metadataB);

        // Both have short name "User" but different namespaces, so the
        // hash prefix must disambiguate them.
        preg_match('/class (N[a-f0-9]{8}_UserDenormalizer)/', $codeA, $matchA);
        preg_match('/class (N[a-f0-9]{8}_UserDenormalizer)/', $codeB, $matchB);

        $this->assertNotEmpty($matchA[1] ?? null);
        $this->assertNotEmpty($matchB[1] ?? null);
        $this->assertNotSame($matchA[1], $matchB[1]);
    }

    public function testGeneratedCodeIsSyntacticallyValidPhp(): void
    {
        // A smoke test that catches obvious syntax regressions without
        // needing the full serializer chain.
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(PersonFixture::class);

        $path = $this->writer->write($metadata);

        $output = [];
        $exitCode = 0;
        exec(sprintf('%s -l %s 2>&1', escapeshellarg(PHP_BINARY), escapeshellarg($path)), $output, $exitCode);

        $this->assertSame(0, $exitCode, sprintf("Generated file failed php -l:\n%s", implode("\n", $output)));
    }

    public function testGeneratedCodeIsSyntacticallyValidForWitherFixture(): void
    {
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(WitherFixture::class);

        $path = $this->writer->write($metadata);

        $output = [];
        $exitCode = 0;
        exec(sprintf('%s -l %s 2>&1', escapeshellarg(PHP_BINARY), escapeshellarg($path)), $output, $exitCode);

        $this->assertSame(0, $exitCode, sprintf("Generated file failed php -l:\n%s", implode("\n", $output)));
    }

    public function testGeneratedCodeIsSyntacticallyValidForSetterFixture(): void
    {
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor(SetterFixture::class);

        $path = $this->writer->write($metadata);

        $output = [];
        $exitCode = 0;
        exec(sprintf('%s -l %s 2>&1', escapeshellarg(PHP_BINARY), escapeshellarg($path)), $output, $exitCode);

        $this->assertSame(0, $exitCode, sprintf("Generated file failed php -l:\n%s", implode("\n", $output)));
    }

    public function testGetMetadataFactoryReturnsInjectedFactory(): void
    {
        $factory = $this->generator->getMetadataFactory();

        $this->assertSame($factory, $this->generator->getMetadataFactory());
    }

    public function testUnaliasedParameterEmitsSingleExtractCall(): void
    {
        // SimpleBlog carries NO `#[SerializedName]` attributes. The
        // generator's chained-call machinery must NOT kick in for this
        // fixture — each constructor parameter should still resolve to a
        // single, non-nested `extract*` call so the generated code stays
        // compact for the common case.
        $code = $this->generate(SimpleBlog::class);

        // The construct() method should have a flat `extractString($data, 'title', ...)`
        // for `$title` — no nested `default: $this->extractNullableString(...)`
        // expression.
        $this->assertMatchesRegularExpression(
            "/extractString\\(\\\$data, 'title', required: true, default: null, context: \\\$context\\)/",
            $code,
        );
    }

    public function testAliasedConstructorParameterEmitsChainedExtractCall(): void
    {
        $code = $this->generate(SerializedNameFixture::class);

        // The outer call must read the canonical (serialized) alias.
        // Its `default:` argument must itself be an `extractNullable*`
        // call that reads the PHP-name fallback.
        $this->assertMatchesRegularExpression(
            "/extractString\\(\\\$data, 'email_address', required: true, default: \\\$this->extractNullableString\\(\\\$data, 'emailAddress', required: false, default: null, context: \\\$context\\), context: \\\$context\\)/",
            $code,
        );
    }

    public function testAliasedConstructorParameterOuterCarriesCallerRequestedRequired(): void
    {
        // `$emailAddress` is required (no default, not nullable). The
        // chained-call pattern must surface `required: true` on the OUTER
        // call — otherwise a payload missing both keys would silently
        // produce an empty string instead of the expected
        // MissingRequiredFieldException.
        $code = $this->generate(SerializedNameFixture::class);

        $this->assertMatchesRegularExpression("/extractString\\(\\\$data, 'email_address', required: true,/", $code);
    }

    public function testAliasedConstructorParameterInnerUsesNullableVariantWithRequiredFalse(): void
    {
        // The inner fallback call MUST use the Nullable variant so a
        // missing fallback key can propagate as `null` rather than the
        // non-null `""` sentinel (which would otherwise short-circuit the
        // outer call's required / default decision).
        //
        // It also MUST use `required: false` so the inner call itself
        // does not throw MissingRequiredFieldException when the fallback
        // key is missing — that decision belongs to the outer call, which
        // will re-evaluate it against the canonical key.
        $code = $this->generate(SerializedNameFixture::class);

        $this->assertMatchesRegularExpression(
            "/extractNullableString\\(\\\$data, 'emailAddress', required: false, default: null,/",
            $code,
        );
    }

    public function testAliasedOptionalParameterPreservesUserDefaultAtTheInnermostLayer(): void
    {
        // `$displayName` has a declared `null` default. The deepest
        // fallback call's `default:` argument must carry that declared
        // default verbatim so that when both keys are absent the declared
        // default — not a hard-coded zero-value — is used.
        //
        // For `displayName` the declared default is `null`, which also
        // happens to be the sentinel the chained machinery uses; the
        // regression we guard against here is the inner call accidentally
        // being emitted with `required: true` or without `default: null`.
        $code = $this->generate(SerializedNameFixture::class);

        $this->assertMatchesRegularExpression(
            "/extractNullableString\\(\\\$data, 'display_name', required: false, default: \\\$this->extractNullableString\\(\\\$data, 'displayName', required: false, default: null, context: \\\$context\\), context: \\\$context\\)/",
            $code,
        );
    }

    public function testAliasedPopulatePhasePropertyEmitsChainedExtractCall(): void
    {
        // `$homePage` is a non-constructor public mutable property with a
        // `#[SerializedName]` attribute. The chained-call pattern must
        // apply identically in populate() as it does in construct().
        $code = $this->generate(SerializedNameFixture::class);

        $this->assertMatchesRegularExpression(
            "/\\\$object->homePage = \\\$this->extractNullableString\\(\\\$data, 'home_page', required: false, default: \\\$this->extractNullableString\\(\\\$data, 'homePage', required: false, default: null, context: \\\$context\\), context: \\\$context\\)/",
            $code,
        );
    }

    public function testAliasedPopulatePhaseGuardAcceptsEitherKey(): void
    {
        // The populate() if-guard must accept EITHER alias by OR-ing the
        // two `array_key_exists` checks — otherwise a payload that only
        // supplies the fallback key would skip the assignment entirely.
        $code = $this->generate(SerializedNameFixture::class);

        $this->assertMatchesRegularExpression(
            "/array_key_exists\\('home_page', \\\$data\\) \\|\\| array_key_exists\\('homePage', \\\$data\\)/",
            $code,
        );
    }

    public function testAliasedConstructorSkipMapIncludesBothAliases(): void
    {
        // Both the canonical AND fallback keys must land in the skip map
        // so that when a fresh instance is built via construct(), the
        // populate() phase does not accidentally rewrite a constructor
        // field just because the fallback key happened to be the one
        // present in the payload.
        $code = $this->generate(SerializedNameFixture::class);

        // The skip map contains a ['email_address', 'emailAddress', ...] entry.
        $this->assertMatchesRegularExpression(
            "/array_fill_keys\\(\\[[^\\]]*'email_address'[^\\]]*'emailAddress'[^\\]]*\\]/",
            $code,
        );
    }

    public function testUnaliasedPopulatePhaseGuardUsesSingleKeyExistsCheck(): void
    {
        // PersonFixture has a nickname populate-phase field with NO alias,
        // so the populate() guard must stay compact — no OR-chain of
        // `array_key_exists` calls for fields that only have one key.
        $code = $this->generate(PersonFixture::class);

        // The `nickname` guard should be a plain single-key check.
        $this->assertMatchesRegularExpression(
            "/array_key_exists\\('nickname', \\\$data\\) && !isset\\(\\\$skip\\['nickname'\\]\\)/",
            $code,
        );
    }

    public function testUnaliasedPopulateExtractCallIsNotChained(): void
    {
        // The unaliased populate branch must emit a flat `extract*` call
        // without a nested inner call — the chained pattern is reserved
        // for fields that genuinely need the fallback.
        $code = $this->generate(PersonFixture::class);

        // The $nickname assignment must NOT contain a nested extract call
        // in its `default:` argument. We assert the compact shape directly.
        $this->assertMatchesRegularExpression(
            "/\\\$object->nickname = \\\$this->extractNullableString\\(\\\$data, 'nickname', required: false, default: null, context: \\\$context\\);/",
            $code,
        );
    }

    /**
     * Convenience helper that generates the denormalizer source for the given
     * target FQCN and returns the full PHP source string.
     *
     * @param class-string $targetFqcn
     */
    private function generate(string $targetFqcn): string
    {
        $metadata = $this->generator->getMetadataFactory()->getMetadataFor($targetFqcn);

        return $this->generator->generate($metadata);
    }
}
