<?php

declare(strict_types=1);

namespace RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer;

/**
 * Marker interface for all denormalizer classes generated by the Buildable Serializer Bundle.
 *
 * Every PHP denormalizer emitted by {@see \RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerGenerator}
 * must implement this interface. The presence of this interface is the sole criterion used by
 * {@see \RemcoSmitsDev\BuildableSerializerBundle\DependencyInjection\Compiler\RegisterGeneratedDenormalizersPass}
 * to identify which classes in the generated classmap should be registered as Symfony Serializer
 * denormalizer services.
 *
 * Implementing classes are automatically tagged with `serializer.denormalizer` at a high priority
 * so they take precedence over Symfony's built-in reflection-based denormalizers for the domain
 * models they handle.
 *
 * Example generated denormalizer skeleton:
 *
 * ```php
 * final class UserDenormalizer implements GeneratedDenormalizerInterface, DenormalizerInterface, DenormalizerAwareInterface
 * {
 *     use GeneratedDenormalizerTrait;
 *
 *     public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): User { ... }
 *     public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool { ... }
 *     public function getSupportedTypes(?string $format): array { ... }
 * }
 * ```
 *
 * @see \RemcoSmitsDev\BuildableSerializerBundle\DependencyInjection\Compiler\RegisterGeneratedDenormalizersPass
 * @see \RemcoSmitsDev\BuildableSerializerBundle\Generator\Denormalizer\DenormalizerGenerator
 * @see \RemcoSmitsDev\BuildableSerializerBundle\CacheWarmer\DenormalizerCacheWarmer
 */
interface GeneratedDenormalizerInterface {}
