services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Metadata\ConstructorMetadataExtractor:
    arguments:
      $propertyInfoExtractor: "@property_info"

  RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory:
    arguments:
      $propertyInfoExtractor: "@property_info"
      $constructorMetadataExtractor: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\ConstructorMetadataExtractor'
    tags:
      - { name: buildable_serializer.metadata_factory }

  buildable_serializer.discovery.normalizers:
    class: RemcoSmitsDev\BuildableSerializerBundle\Discovery\FinderClassDiscovery
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $paths: "%buildable_serializer.normalizers.paths%"

  buildable_serializer.discovery.denormalizers:
    class: RemcoSmitsDev\BuildableSerializerBundle\Discovery\FinderClassDiscovery
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $paths: "%buildable_serializer.denormalizers.paths%"

  RemcoSmitsDev\BuildableSerializerBundle\Discovery\ClassDiscoveryInterface:
    alias: "buildable_serializer.discovery.normalizers"
    public: false

  # Normalizer

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator:
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $generatedNamespace: 'BuildableSerializerBundle\Generated'
      $features: "%buildable_serializer.normalizers.features%"

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGeneratorInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerPathResolver:
    public: true
    arguments:
      $cacheDir: "%kernel.cache_dir%/buildable_serializer"
      $generatedNamespace: 'BuildableSerializerBundle\Generated'

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerPathResolverInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerPathResolver'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerWriter:
    public: true
    arguments:
      $generator: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator'
      $pathResolver: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerPathResolver'

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerWriterInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerWriter'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\CacheWarmer\NormalizerCacheWarmer:
    arguments:
      $writer: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerWriter'
      $discovery: "@buildable_serializer.discovery.normalizers"
    tags:
      - { name: kernel.cache_warmer, priority: 10 }

  # Denormalizer

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerGenerator:
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $generatedNamespace: 'BuildableSerializerBundle\Generated'
      $features: "%buildable_serializer.denormalizers.features%"

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerGeneratorInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerGenerator'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerPathResolver:
    public: true
    arguments:
      $cacheDir: "%kernel.cache_dir%/buildable_serializer"
      $generatedNamespace: 'BuildableSerializerBundle\Generated'

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerPathResolverInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerPathResolver'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerWriter:
    public: true
    arguments:
      $generator: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerGenerator'
      $pathResolver: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerPathResolver'

  RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerWriterInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerWriter'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\CacheWarmer\DenormalizerCacheWarmer:
    arguments:
      $writer: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\DenormalizerWriter'
      $discovery: "@buildable_serializer.discovery.denormalizers"
    tags:
      - { name: kernel.cache_warmer, priority: 10 }
