services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory:
    arguments:
      $propertyInfoExtractor: "@property_info"
    tags:
      - { name: buildable_serializer.metadata_factory }

  buildable_serializer.discovery.normalizers:
    class: RemcoSmitsDev\BuildableSerializerBundle\Discovery\FinderClassDiscovery
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $paths: "%buildable_serializer.normalizers.paths%"

  buildable_serializer.discovery.denormalizers:
    class: RemcoSmitsDev\BuildableSerializerBundle\Discovery\FinderClassDiscovery
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $paths: "%buildable_serializer.denormalizers.paths%"

  RemcoSmitsDev\BuildableSerializerBundle\Discovery\ClassDiscoveryInterface:
    alias: "buildable_serializer.discovery.normalizers"
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator:
    arguments:
      $metadataFactory: '@RemcoSmitsDev\BuildableSerializerBundle\Metadata\MetadataFactory'
      $cacheDir: "%kernel.cache_dir%/buildable_serializer"
      $generatedNamespace: 'BuildableSerializerBundle\Generated'
      $features: "%buildable_serializer.normalizers.features%"

  RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGeneratorInterface:
    alias: 'RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator'
    public: false

  RemcoSmitsDev\BuildableSerializerBundle\CacheWarmer\NormalizerCacheWarmer:
    arguments:
      $generator: '@RemcoSmitsDev\BuildableSerializerBundle\Generator\NormalizerGenerator'
      $discovery: "@buildable_serializer.discovery.normalizers"
    tags:
      - { name: kernel.cache_warmer, priority: 10 }
